//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZslCustomsAssist.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZslCustomsAssist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 hH4Ve6MacXEyeBt1 的本地化字符串。
        /// </summary>
        internal static string AESIV {
            get {
                return ResourceManager.GetString("AESIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Si62Em771w5PEUY3 的本地化字符串。
        /// </summary>
        internal static string AESKey {
            get {
                return ResourceManager.GetString("AESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://szdtsp.szcport.cn:8443/szcport/ 的本地化字符串。
        /// </summary>
        internal static string CloudServicesUrl {
            get {
                return ResourceManager.GetString("CloudServicesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://sgtdrq.szcport.cn:8443/szcport/ 的本地化字符串。
        /// </summary>
        internal static string DataQueryServicesUrl {
            get {
                return ResourceManager.GetString("DataQueryServicesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 abcd@1234 的本地化字符串。
        /// </summary>
        internal static string ElectSignKey {
            get {
                return ResourceManager.GetString("ElectSignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://202.103.147.74:8888/pdf/base64Encryption 的本地化字符串。
        /// </summary>
        internal static string ElectSignUrl {
            get {
                return ResourceManager.GetString("ElectSignUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string EnableAES {
            get {
                return ResourceManager.GetString("EnableAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6666 的本地化字符串。
        /// </summary>
        internal static string HttpServicePort {
            get {
                return ResourceManager.GetString("HttpServicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string IsBindingCard {
            get {
                return ResourceManager.GetString("IsBindingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string IsBindingIp {
            get {
                return ResourceManager.GetString("IsBindingIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string IsVerifySign {
            get {
                return ResourceManager.GetString("IsVerifySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string IsWithOutCard {
            get {
                return ResourceManager.GetString("IsWithOutCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中商旅报关辅助系统客户端 的本地化字符串。
        /// </summary>
        internal static string MainFormName {
            get {
                return ResourceManager.GetString("MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 的本地化字符串。
        /// </summary>
        internal static string MainLogLinage {
            get {
                return ResourceManager.GetString("MainLogLinage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string MinReceiveThreads {
            get {
                return ResourceManager.GetString("MinReceiveThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string MinSendThreads {
            get {
                return ResourceManager.GetString("MinSendThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MonitorUpdateTemp 的本地化字符串。
        /// </summary>
        internal static string MonitorUpdateTempDirectory {
            get {
                return ResourceManager.GetString("MonitorUpdateTempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2100060004461 的本地化字符串。
        /// </summary>
        internal static string RestrictedCardNo {
            get {
                return ResourceManager.GetString("RestrictedCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string RestrictedIP {
            get {
                return ResourceManager.GetString("RestrictedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FORMAL 的本地化字符串。
        /// </summary>
        internal static string RunningEnvironment {
            get {
                return ResourceManager.GetString("RunningEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CBTUpdateLog.log 的本地化字符串。
        /// </summary>
        internal static string UpdateLogFileName {
            get {
                return ResourceManager.GetString("UpdateLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://114.67.232.251 的本地化字符串。
        /// </summary>
        internal static string ZslApiServicesUrl {
            get {
                return ResourceManager.GetString("ZslApiServicesUrl", resourceCulture);
            }
        }
    }
}
